services:
    directus:
        image: directus/directus:11.17.0
        ports:
            - 8055:8055
        volumes:
            - ./src/database:/directus/database
            - ./src/uploads:/directus/uploads
            - ./extensions:/directus/extensions
        environment:
            SECRET: "replace-with-random-value"
            DB_CLIENT: "sqlite3"
            DB_FILENAME: "/directus/database/data.db"
            WEBSOCKETS_ENABLED: "true"
            ADMIN_EMAIL: "[EMAIL_ADDRESS]"
            ADMIN_PASSWORD: "tabernam-admin"
            ADMIN_TOKEN: "tabernam-admin-token"
